[build]
  publish = "build/"
  command = "npm run build"
[context.production]
  environment = { "NODE_ENV" = "production"}

[[redirects]]
  from = "/github/callback"
  to = "/"
  status = 200
  force = true
