[build]
  publish = "build/"
[context.production]
  command = "npm run build"
  [context.production.environment]
    API_HOST = "https://d1fc9ef5.ngrok.io"
    NODE_VERSION = "12.12.0"
    GITHUB_CLIENT_ID='bd96258260f769a56370'
    REDIRECT_URI='https://centrifuge-demo.netlify.app/github/callback', POLKASCAN_URI= 'https://polkascan.io/pre/centrifuge-amber-cc2/transaction/'

[[redirects]]
  from = "/github/callback"
  to = "/"
  status = 200
  force = true
