export const SIGNUP_UPDATE_FORM_FIELD = 'SIGNUP/UPDATE_FORM_FIELD';
export const SIGNUP_START = 'SIGNUP/SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP/SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP/SIGNUP_ERROR';
